name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install X11 dependencies
        run: |
          apt-get install xorg openbox

      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          username: "shuaiscott"
          password: ${{ secrets.PAT }}
          repository: shuaiscott/kindle-gui
          tags: latest
